### ISSUE TITLE
[Req] Window Title

### ISSUE THREAD

**Issue by SoraHjort** [jonloveslegos/ChecksFinder#2]
![image](https://github.com/user-attachments/assets/a9b01005-e055-4745-b146-bc54d23c0f9a)

"Created with GameMaker" should be changed to be "ChecksFinder". It just feels odd to be like that is all.

Though if you want more to that, perhaps the title could additionally changed on connecting to the server to also have the slot name in the window title. Such as "ChecksFinder - Player". I can see that being useful for streamers who decide to run multiple simultaneous instances, since atleast with OBS you can capture based on window titles.

Or if not that maybe have the title customizable in the config? That way any streamer that decides to go down that silliness can do it simply by having multiple copies of ChecksFinder.

**Comment by SunCatMC** [comment]
implemented second suggestion in 1.2.7

**Comment by SunCatMC** [comment]
https://github.com/jonloveslegos/ChecksFinder/releases/tag/v1.2.7
